### ISSUE TITLE
Release ES5 javascript

### ISSUE THREAD

**Issue by fabiosantoscode** [WebReflection/flatted#10]
Please, using babel or manually, release ES5 javascript, for node 0.10 compatibility

**Comment by WebReflection** [comment]
wut?

**Comment by WebReflection** [comment]
so ... from the README

```js
// ESM
import {parse, stringify} from 'flatted/esm';

// CJS
const {parse, stringify} = require('flatted/cjs');
```

**Comment by WebReflection** [comment]
P.S. if you want the browser version you can use [unkpg/flatted](https://unpkg.com/flatted) which is ES3 compatible

**Comment by WebReflection** [comment]
P.S.2 the code is [ES5 compatible already](https://github.com/WebReflection/flatted#compatibility), in case you have opened this bug out of instinct ... otherwise please find the line that breaks in your node 0.10 https://github.com/WebReflection/flatted/blob/master/cjs/index.js

However, you need `Map`, `Set`, `Object.keys`, and `Array.prototype.reduce` so you should have some polyfill before using flatted.

**Comment by andreidiaconescu** [comment]
How can we actually use this in a browser, like an example would be really useful.

**Comment by WebReflection** [comment]
any package can be used by a browser ... not sure what you are mentioning here ...

```js
import {parse, stringify} from 'https://cdn.skypack.dev/flatted';
```

**Comment by andreidiaconescu** [comment]
i found that it can be used in a browser like this:

HTML:
```
<script src="https://unpkg.com/flatted@3.2.7/min.js"></script>
```

JS:
```
Flatted.stringify(someVar);
```
