### ISSUE TITLE
Not producing Indexes, is this possible ?

### ISSUE THREAD

**Issue by appsolutegeek** [WebReflection/flatted#17]
Hi,

When i use stringify it produces an index first i.e.

```
[{"level":"1","logger":"2","message":"3","timestamp":"4","otherData":"5","stack":"6","service":"7"},"DEBUG","authentication.ts","db: mongodb is connected","2019-03-26T10:56:43.357Z",[],"frontend","front-api"]
```
Its probably quite easy to strip - but is there anyway to tell flatted not to produce the index i.e this

```
{"level":"1","logger":"2","message":"3","timestamp":"4","otherData":"5","stack":"6","service":"7"}
```

Also when a circular reference is found, does it still produce valid JSON ?

[Circluar] ??

Thanks in advance

**Comment by WebReflection** [comment]
https://github.com/WebReflection/flatted#how-does-it-work-

**Comment by WebReflection** [comment]
if you reed `[Circular]` is because there is a circular reference which means flatted worked as expected.

The output produced by flatted can be consumed by JSON but only parsed back by flatted.

You should never care about what kind of output `flatted.stringify` produce, as long as you can retrieve back your objects once you use `flatted.parse`.

However, the way it works is explained in the little README as previously linked.
