### ISSUE TITLE
Add an option to use a different JSON parser/stringifier

### ISSUE THREAD

**Issue by tjjfvi** [WebReflection/flatted#27]
It would be nice if one could set `flatted` to use something different as the JSON parser/stringifier. For example, I would like to use flatted in conjunction with [MessagePack](https://msgpack.org/), but currently I believe I would have to do something like:
```js
msgpack.stringify(JSON.parse(flatted.stringify(obj)));
flatted.parse(JSON.stringify(msgpack.parse(buf)));
```
Alternatively, an option to not parse/stringify the input/output would work as well, because it would remove the need to do the `JSON.parse`/`JSON.stringify`.

**Comment by WebReflection** [comment]
The _flatted_ API is purposely 1:1 with the JSON one, and adding anything different will likely diverge and doom the signature of flatted forever.

On top of that, the JSON parser, with its functionalities, is mandatory to make this work, see:
https://github.com/WebReflection/flatted/blob/master/esm/index.js#L62-L65

That means there's no easy way around current flatted implementation, so I think you'll need that dance.

However, I am not familiar with `msgpack`, so that if it has exact same JSON API too, you can temporarily assign its methods and put these back on parsing.

```js
import Flatted from 'flatted';
import MessagePack from 'msgpack';
const MyJSON = {
  parse(...args) {
    const {parse} = JSON;
    JSON.parse = MessagePack.parse;
    const result = Flatted.parse(...args);
    JSON.parse = parse;
    return result;
  },
  stringify() {
    const {stringify} = JSON;
    JSON.stringify = MessagePack.stringify;
    const result = Flatted.stringify(...args);
    JSON.stringify = stringify;
    return result;
  }
};
```

It's not super clean, but if it works, it's surely faster than your current double dance.
