### ISSUE TITLE
Output format is unique to flatted

### ISSUE THREAD

**Issue by joshuaaa** [WebReflection/flatted#32]
**Problem**

The npm module circular-json has been deprecated, and should be replaced by flatted.

No problem, they have the same method signature.  However, after switching to flatted, we started having errors.  When I dug into it, I found that the generated json is very different.  

Specifically, given:

```
const CircularJSON = require('circular-json');
const Flatted = require('flatted');
const obj = { a: 1, b: 'two', c: { c_1: 9, c_2: 'nested'} };
console.log('circular-json:', CircularJSON.stringify(obj));
console.log('flatted:', Flatted.stringify(obj));
```

The result is:

```
circular-json: {"a":1,"b":"two","c":{"c_1":9,"c_2":"nested"}}
flatted: [{"a":1,"b":"1","c":"2"},"two",{"c_1":9,"c_2":"3"},"nested"]
```

I'm sorry to say this, but the new output string is garbage.  I'm sure that this is more performant, or less prone to bugs, or something, but it is also useless if you are trying to send data to another system that doesn't use flatted.

**Question**

Is there a way to tell flatted to use a normal json format?  Or should I use just use json-stringify-safe instead (would rather not, it appears abandoned)?

**Comment by WebReflection** [comment]
**Answer**

No, and I'm not wasting time explaining anything since you consider this module garbage.

**Comment by revelt** [comment]
Whoever came here looking why their circular JSON is not indented properly (quick non-circular stringify output example):

<img width="206" alt="json-stringify-safe" src="https://user-images.githubusercontent.com/8344688/69897159-8dbc0b80-133f-11ea-9c9f-6bbc36652dea.png">

if you do want indentation right now, switch to [json-stringify-safe](https://www.npmjs.com/package/json-stringify-safe), it is not abandoned, it just works.

It would be nice if author of this package aligned the default indentation to match `JSON.stringify`.

**Comment by WebReflection** [comment]
@revelt the indentation is the one provided by `JSON.stringify`. This module, as well as CircularJSON, is just a replacer-reviver on top of native API.

In **both** cases, the outcome was specialized, and the fact people using CircularJSON thought it was OK to pass along the output to other programming languages was the biggest footgun of them all, which is why Flatted clearly produces an output that requires Flatted to convert it back, as well as CircularJSON produces an output that **only** CircularJSON should convert back ... like, **always**, **no exceptions included**, because if a single circular reference gets changed elsewhere, the whole module breaks.

So no, I won't do anything with the outcome produced natively by JSON, but I am also closing this issue because **there is no issue here**, and everything is explained in README.
