### ISSUE TITLE
Not Able to Parse JSON

### ISSUE THREAD

**Issue by baljeet-c3t** [WebReflection/flatted#35]
Hi

First of all thanks for this lib. I have saved the `stringify(data)` response. But, now I need to convert it back to normal response. But I'm still getting the same output even after using `parse(stringify(data))` method.

<img width="380" alt="Annotation 2020-04-09 175824" src="https://user-images.githubusercontent.com/61836031/78895299-33208200-7a8c-11ea-92f4-d3a0f209dbaf.png">

Here you can see the parsed response is same as the response received from the api. It should be similar to JSON export (The first response in the image). Am I missing something.

I'm using `fetch` for API call, following is inside the then block
`console.log('JSON API Response:', data);
console.log('Flatted Parsed Data', parse(stringify(data)));`

**Comment by WebReflection** [comment]
https://github.com/WebReflection/flatted#flatted-vs-json

**Comment by baljeet-c3t** [comment]
Hi,

If you look closely, I'm using the method described in the link `Flatted.parse(Flatted.stringify(data))`. Still not getting the correct response.

I'm using CJS
`const {parse, stringify} = require('flatted/cjs');`

**Comment by WebReflection** [comment]
A screenshot doesn't help. If I don't have a way to test anything you are saying, there's no point in discussing. Please note this module has million users, your issue is basically that it doesn't work, which is unlikely the case, thanks to 100% code coverage too.

In few words, this issue is badly filed:

  * nothing to test
  * no code to review ... but ...
  * this library works for sure, hence I've closed this issue.

If you provide a way to reproduce anything you are saying that doesn't work, then I might try to help.
