### ISSUE TITLE
v3.0.2 broke es5 support

### ISSUE THREAD

**Issue by hackel** [WebReflection/flatted#41]
As of v3.0.2, the `{cjs,esm}/index.js` builds are including arrow functions.  This breaks using the package in IE11, unfortunately.  I'm only using flatted as a dependency of another package which I am already manually transpiling, but it took quite some time to debug that now I also need to transpile flatted, since before it worked fine.

If you don't want to keep supporting es5 that's totally understandable, but it's a pretty major breaking change that should be documented somewhere.

**Comment by WebReflection** [comment]
It's been like this "*forever*" for pretty much every module of mine ... the ES5 is https://github.com/WebReflection/flatted/blob/master/index.js and minified through CDNs like https://unpkg.com/flatted

if you use a module system you *gotta* transpile that regardless, because IE11 doesn't understand `import` or `require`, and with that, you need to transpile modules.

If that doesn't happen with your bundle, it's a bundle issue/configuration problem.

It's about the time developers learn how to distribute ES5 to IE and ES2015 to every other non IE browser, and I've written plenty of solutions, hints, articles, regarding this.

If you serve files to IE, and you bundle these, be sure your bundler does what it's supposed to do.

As summary:
  * the whole source is written in ES2015, it's not just *arrow functions*, it's *const* and everything else
  * if you want to support IE11 without bundlers, use the appropriate file already transpiled
  * if you use bundlers, be sure these are capable of transpiling for *your* target browsers

**Comment by hackel** [comment]
@WebReflection Yes, that's all good info, but the point is it's still a breaking change and you don't even have a CHANGELOG in this project or any release notes that I could find (let me know if I'm missing this).  This was not an issue in v2.  Your package.json points to `./cjs/index.js` so '/index.js' will never be used unless explicitly specified, but this isn't mentioned anywhere in the documentation, and it's even more opaque when this is only pulled in as a dependency of another package.

I don't waste time transpiling packages unless I *know* that I need to.  Bundling (handling import/require) is not the same as transpiling with Babel.  I always exclude node_modules entirely and individually transpile any packages that distribute es2015+ code to optimize the build time, and I think this is a common practice.

It would just be really helpful if you would communicate changes to your users with a CHANGELOG.

Thanks for your work on this package!

**Comment by WebReflection** [comment]
>  This was not an issue in v2

Yeah, *v3* was a major, and *3.0.2* was a patch for the major, which was meant to ship as modern JS.

The *3* was meant to break after this commit https://github.com/WebReflection/flatted/commit/93250d343dd8dae93dc3db929441035aa1c3212b

>  I always exclude node_modules entirely and individually transpile any packages that distribute es2015+ code to optimize the build time, and I think this is a common practice.

it's fragile as practice, and it's not common to me, but if you're comfortable with such practice, I'm afraid if you want *flatted* to work in IE11 you need to transpile it *or* you require/import a part the other files.

> It would just be really helpful if you would communicate changes to your users with a CHANGELOG.

I usually do write a note in the readme, but major bumps are often self-explanatory: there is a breaking change, and as this module is downloaded 49 million times per month, it's surprising you've realized this only recently, otherwise I would've updated the README.

At this point, bumping for something nobody else had issues with, doesn't look important so, apologies for the inconvenience, but *flatted* is modern code, and IE11 users are fading away, so I don't think I should write that if you target IE11 you gotta be sure each module gets transpiled, as that notice would be the same for every single project of mine, hence it'll be like the coockies notification: nobody cares 😅
