### ISSUE TITLE
parse(stringity(ob)) does not produce a copy

### ISSUE THREAD

**Issue by Akxe** [WebReflection/flatted#44]
I have made as simple stackblitz as possible: https://stackblitz.com/edit/flatted-stringify-error?file=index.ts

This is the key point of it:
```js
const carrier = {
  id: "Carrier 1",
  map: new Map()
};

const period = {
  id: "Period 1",
  carriers: new Set([carrier])
};

carrier.map.set(period, {});

const result = stringify([carrier]);
console.log(parse(result));
```

**Comment by token-cjg** [comment]
Apparently you need to use some form of reviver I think.  See for instance here: https://github.com/WebReflection/circular-json/issues/44#issuecomment-388026349.

I'm a bit at a loss how to implement this myself though.  I have a similar issue where I have a type, eg

```
let originalTurkeys: { [index: string]: Turkey } = 
[ 
  {"simon": { "weight": 3, "height": 4} }, 
  { "paul": { "weight": 7, "height": 2} } 
];
function reviver(key, value) {
  // do something appropriate ...?
}
turkeys = Flatted.stringify(originalTurkeys);
this.turkeys = Flatted.parse(turkeys, reviver);
```

The example from the issue filed in CircularJSON is for a Class, but I am interested in how to revive a flatted object for a Type.

**Comment by WebReflection** [comment]
Honestly, I don’t understand which part of circular JSON is not clear in this project. Every N weeks, somebody complains about not serializing stuff that has never been serializable via JSON. Now, I had a bad day today and I apology if this answer sounds rude or something, but what exactly do you expect from a JSON parser that understands only what JSON can understand?

**Comment by WebReflection** [comment]
P.S. StackOverflow with a question like “how do I stingily and parse Map and Set instances in JSON?” would give you much more content, details, or answers, than anything a library which goal is to avoid issues with circular references could, and I wouldn’t mind myself answering that in there ... but here, you’re asking completely off-topic/out of scope questions that are unrelated with this project, and I don’t want to answer in here anything that has nothing to do with this JSON based library.
Thanks for your understanding.

**Comment by WebReflection** [comment]
P.S.2 if you understand how to serialize classes instances, Map is an .entries() away, and Set is a .keys() away from your goal.

**Comment by token-cjg** [comment]
I'm sorry to hear that you had a bad day.

Thanks for creating this useful tool.  I upvoted the above question but ended up figuring out how to solve my problem with use of your tool.

My usecase is setting and retrieving javascript objects with circular references in [RedisJSON](https://redislabs.com/blog/redis-as-a-json-store/).  I was trying to set a key with `Flatted.stringify(objectWithCircularTypeReference)` and that worked liked a charm.

My issue was retrieving the key when it was empty with `Flatted.parse(retrievedFlattedObjectStoredInRedisJSON)`.

`Flatted.parse({})` blows up with

 ```
   const input = $parse(text, Primitives).map(primitives);
                                         ^

TypeError: $parse(...).map is not a function
```

I ended up going down a rabbithole of trying to understand revivers and other things - I thought that maybe I needed to implement one for your Flatted.parse (which I see it does support, again good work supporting that).  I found [this interesting snippet](https://gist.github.com/kolodny/8043084) to extend JSON.parse in javascript to support circular references, and also [an earlier issue filed in the Circular Reference library](https://github.com/WebReflection/circular-json/issues/44), where revivers were mentioned.

Turns out that the issue was fairly straightforward to solve, I just copied your code in flatted/index.js, enough to support parse https://github.com/WebReflection/flatted/blob/master/index.js#L66-L74 and then inserted a new line [here](https://github.com/WebReflection/flatted/blob/master/index.js#L67).

```
export function flattedParse (text, reviver) {
	if (text === "{}") return {}; // handles edge case when text is the empty object
	const input = JSON.parse(text, Primitives).map(primitives);
	const value = input[0];
	const $ = reviver || noop;
	const tmp = typeof value === object && value ? revive(input, new Set(), value, $) : value;
	return $.call({
		"": tmp
	}, "", tmp);
}
```

That solved the problem for me.

**Comment by WebReflection** [comment]
The issue is that you cannot parse arbitrary JSON with flatted, and this is explained in the index. Your “solution” is a hack around the fact you’re not controlling the flatted.parse input, and being a hack against the most basic rule of this project, or any specialized parser, it won’t land.

try to stringify an empty object and use **that** as empty entry, or use a reviver that takes care of your use case.

Yet, the initial issue had no hints about this, and used Map and Set in the mix.

**Comment by Akxe** [comment]
Hi, it really did not mean to be rude whatsoever. I was looking for any library that would accept any data (with circular references) to parse that.

When I stumbled upon this library I have read through the readme and saw this line:
> As it is for every other specialized format capable of serializing and deserializing circular data...

With this in mind, I thought that every native object/class is serializable. I tried my test case and it failed. Since it failed I thought of raising an issue. Either you would say this is not in the scope of this project or that it is indeed a bug.

------

EDIT: I wanted to keep the text above...

I was re-reading the readme just now more than 3 times and just now I figured out that the library is not supposed to sterilize `Set`, `Map` and others, but only that it requires them to run. With this information the reason you are upset it now cleaner. I can only suggest putting that information more in from of others.

The heading `Compatibility` is somewhat misleading in this context I, in your place, would rename it to requirements, and considered creating heading "serilizable".

**Comment by WebReflection** [comment]
> I can only suggest putting that information more in from of others.

it's not this library, it's [the JSON standard](https://www.json.org/json-en.html).

this library serializes and de-serializes with its own proprietary format **JSON** and nothing else.

there are ways to parse and revive global/known classes but that's not standard and completely out of this library scope.

I hope this answers further.

**Comment by WebReflection** [comment]
In case you missed it though, the [README](https://github.com/WebReflection/flatted#flatted-vs-json) is clear.

![Screenshot from 2021-04-20 12-27-16](https://user-images.githubusercontent.com/85749/115381472-e3fb4a00-a1d3-11eb-92e9-4d781ddbf24a.png)

And the first line is literally:

> A super light (0.5K) and fast circular **JSON** parser

Accordingly, you can do everything is possible to do with JSON without worrying about circular references and ... **nothing else**.

Closing this as I think all answers have been given 👋
