### ISSUE TITLE
JSON.parse('["a"]',function(k,v){return v == null && k !== '' ? void 0 : v})

### ISSUE THREAD

**Issue by GuoSirius** [WebReflection/flatted#45]
```javascript
JSON.parse('["a"]',function(k,v){return v == null && k !== '' ? void 0 : v}) 
```

In IE11 : exception 

![image](https://user-images.githubusercontent.com/48358523/113813443-7d713780-97a2-11eb-8570-e4fb9824e235.png)

**Comment by GuoSirius** [comment]
3.1.1 ERROR

3.1.0 OK

**Comment by WebReflection** [comment]
You cannot parse JSON with Flatted serialized strings, the same way you cannot parse, with Flatted, JSON serialized strings.

The format is different, so that `Flatted.stringify(["a"])` produces `[["1"],"a"]`, not `["a"]`, and `Flatted.parse('[["1"],"a"]', function(k,v){return v == null && k !== '' ? void 0 : v})` produces `["a"]` without any error.

This is [written in the README too](https://github.com/WebReflection/flatted#flatted-vs-json).
