### ISSUE TITLE
cannot use in typescript

### ISSUE THREAD

**Issue by y-nk** [WebReflection/flatted#75]
When importing:

```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("flatted")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '~/package.json'.
```

matching tsconfig:

```json
{
  "compilerOptions": {
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "target": "esnext",
    "lib": ["esnext"],

    "declaration": true,
    "esModuleInterop": true,
    "incremental": true,
    "removeComments": true,
    "strict": true,
    "alwaysStrict": true,
    "noImplicitThis": false,
    "noImplicitAny": false,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowUnreachableCode": false,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strictPropertyInitialization": false
  }
}
```

**Comment by WebReflection** [comment]
* the [type](https://github.com/WebReflection/flatted/blob/main/package.json#L53) is `module`
  * the [exports](https://github.com/WebReflection/flatted/blob/main/package.json#L54-L59) are defined
  * the [main](https://github.com/WebReflection/flatted/blob/main/package.json#L7) is correct
  * the [module](https://github.com/WebReflection/flatted/blob/main/package.json#L52) is correct too

Not only this module uses all possible standard and non standard ways to work in either ESM or CJS, it's downloaded ~140M times per month and I won't change a thing in the `package.json` because nobody else ever mentioned an issue with it.

Changing what worked for years at this point will break more than it fixes so ... I suggest you update your bundler, whatever that is, as it's clearly incapable of dealing with dual modules.

**Comment by y-nk** [comment]
Hello @WebReflection. First of all I didn't mean to be harsh in my original report, and i'm sorry if you felt this way (by looking at the strength of your answer).

I'm simply pointing out a fairly common typescript configuration for 2023+ projects. I'm not using any bundler, but plain tsc otherwise i would have checked this first and maybe included relevant configuration.

I've made a small repro which is here which produces the same error:

<img width="702" alt="image" src="https://github.com/WebReflection/flatted/assets/411625/41cdbb68-c12a-4173-abd6-dd6a66199aee">

https://codesandbox.io/p/devbox/flatted-typescript-c3rht3

It's only flatted TSC and that config.

---

> because nobody else ever mentioned an issue with it.
For every issue there's a first, otherwise nobody will ever file an issue 😅 

> Changing what worked for years at this point will break more than it fixes so ...
I agree and i'm not strongly asking for any change at this point, all i wanted is to raise this and see if it was something which could be interesting for you, you know... just helping out. If you asked me I would have helped with a PR as well.

**Comment by WebReflection** [comment]
> First of all I didn't mean to be harsh in my original report, and i'm sorry if you felt this way (by looking at the strength of your answer).

@y-nk nothing about you, it's just tiresome to me all latest bugs here are because of tools and not because of the code but I wanted to underline it's **extremely risky** to me to change anything with this module without breaking more (still tools, not code).


> all i wanted is to raise this and see if it was something which could be interesting for you

understood and appreciated ... the thing is that your error talks about a *CommonJS* module while this module is **everything but CommonJS**, it's actually an **ESM** module first and the `./cjs/package.json` file disambiguate the parsing goal so that no tool that actually understands the standard way modules should be resolved shold ever complain.

My rant is rather that I get "the blame" but this is clearly a TSC issue to me. I will try to replicate though ...

**Comment by WebReflection** [comment]
Apparently I can't access your sandbox but here my thinking? Are you using a static `import` statement within a *CommonJS* file? Because if that's the case, the issue is on you and you should use `const { stringify } = require('flatted')` instead.

**Comment by y-nk** [comment]
thanks for your answer and feedback.

i have updated the sandbox sharing permissions (it was still in draft, i was too much in a hurry)

as you just pointed out, i think the issue is that since i do not have `type: "module"` in _my_ package.json, node import resolves to `main` (the cjs version) while tsc has `moduleResolution: "nodenext"` set. I would believe there's dissonance between both how import (from node) works based on node rules, and how tsc is doing its job as well resolving the modules.

i can't swap easily to `type: module` (because there are ~100 of deps) but so far it seems that cjs modules are ok with it as long as they don't have esm versions.

for now i have resolved this by changing the import to `flatted/esm` which i discovered while hovering the repo.

---

i never meant to send you any blame :) i'm grateful for the package and we're making good use of it so if anything we can help with, please say.

**Comment by WebReflection** [comment]
> I would believe there's dissonance between both how import (from node) works based on node rules, and how tsc is doing its job as well resolving the modules, or is it that tsc just doesn't read exports?

This module uses the *standard way to provide both ESM and CJS* and **tsc** clearly has no idea how to deal with proper packages meant to actually run seamlessly.

Static `import` statements are not allowed in *CommonJS* so NodeJS would have the exact same issue but you can `require("flatted")` or `import "flatted"` or `import("flatted")` without a single issue in all borwsers or NodeJS versions you want.

**tsc** here allows a footgun out of the box and it thinks the module *flatted* is *ESM only* but this stuff should be brought to TSC attention, not to developers that actually wrote the standard way NodeJS resolves modules so I hope there will be a follow up @ **tsc** about this because most of my modules are written as dual module and to date nobody had issues with these so yes, this is a prime indeed 👋
