### ISSUE TITLE
Exclude Go, PHP and Python files from NPM package

### ISSUE THREAD

**Issue by sjerdo** [WebReflection/flatted#76]
Some of our dependencies use this NPM package as a dependency. Unfortunately, this NPM package includes a PHP file.

Can you exclude the php executable file from the distributed NPM package?

**Comment by WebReflection** [comment]
what issue are we trying to solve here? there's Python too, and Go (one day) next to the pipe ... I won't exclude others neithers ... are you having an issue that any `.php` file in your server should be executed when users reach that file? 'cause in here nothing gets executed, so I'd like to understand what is your issue or why, because with over 150 Million download per week, it's hard to welcome breaking changes like this.

**Comment by sjerdo** [comment]
We just had to exclude the `node_modules` folder from our PHP Static Analysing tool to make linting errors go away. That raised the question why a node module should include a PHP file at all. 

Changed the subject of this issue. In my opinion the NPM package should only include files required for Node. Files only needed for Go, Python and PHP should only be exported for these package managers. These files should be add to the `.npmignore` file. This will also reduce the package size.

This might be a breaking change (eg for a 4.0 release) if for some reason some users of this package use NPM for downloading PHP, Go or Python dependencies.. They probably should use Composer, Go Package Manager of Python Package Manager instead.

You might also add a .gitattributes file to exclude some (test) files for tagged releases.

**Comment by WebReflection** [comment]
it's just convenient for me to have all files in the package which is a total of 40.3 kB once unpacked, we're not talking MBs or anything else.

I'd rather have those files not throwing errors on linters but I don't understand your issue in the first place: why are you wasting PHP Static Analysing CPU/RAM/IO time at all if you don't expect PHP files in the *node_modules* folder?

Why that raised the question about "others being wrong" instead of realizing your PHP linter tool should never check `node_modules` folders at all instead?

Why there's no help instead to fix those linting errors if you believe your tool checking folders it shouldn't in the first place should still do that?

I am not planning to do 4 releases if I ever need to change this module as that's just friction so I think I will close this issue as won't fix but you are more than welcome to file a PR that fixes linting errors as long as the suggested change is still readable to me that don't write PHP much these days, thank you!

P.S. now we're over 160 million downloads per week, a major that brings nothing to the plate is not a good major to me.

**Comment by WebReflection** [comment]
also ...

> In my opinion the NPM package should only include files required for Node

NPM contains shell, bash, power shell scripts, text files, sqlite databases, you name it ... it's a repository for the JS ecosystem, nowhere in there is forbidden to ship companions of those files and some module needs GO or Python or even PHP behind the scene so this argument easily fails in the personal opinion category, imho.

Again, if you had security issues or something I wouldn't spend a second and fix that, if you have tools crawling paths they shouldn't and that's the only issue I really don't see the point of changing what works well for many others.

We can agree to disagree but I wanted to add more context.
