### ISSUE TITLE
Document the benefits of compression

### ISSUE THREAD

**Issue by lilouartz** [WebReflection/flatted#79]
Just wanted to say that I stumbled into this project while trying to find a solution for how to transfer deeply complex JSON structure of my payload that was otherwise crashing my browser (https://github.com/jacob-ebey/turbo-stream/issues/33).

Adopting this as a method of JSON "compression" reduced the overall payload size (after brotli) from 848KB to 780KB and the browser is now no longer crashing.

Here is an example of a problematic page: https://pillser.com/brands/21st-century

Super grateful for discovering the project and I thought I will share my experience, as adding it to documentation could help others.

**Comment by WebReflection** [comment]
the compression in your case, if I understood the issue, is more a side-effect of repeated strings not repeated anymore with *flatted*, because strings are used to actually disambiguate indexes while numbers are left alone due their nature (float VS int):

```js
import('https://esm.run/flatted')
  .then(({ stringify }) => stringify([
    { id: 1, txt: "same thing" },
    { id: 2, txt: "same thing" },
  ]))
  .then(console.log);

// produces:
[["1","2"],{"id":1,"txt":"3"},{"id":2,"txt":"3"},"same thing"]
```

See that `"3"`? Index `3` of the root: `"same thing"`.

The index as string refers to both same references and same strings so there you have saving in bigger, repeated, nested structures, but it's not the goal of this library to "*save space*", strictly speaking, rather the one to have a "*serialization that is easy to disambiguate in deserialization*".

A `["nope"]` array would instead produce `[["1"],"nope"]` which is bigger, not smaller, so I am not sure I should somehow mislead users of this package by stating that "*it compresses too*" ... 'cause that's not necessarily true, and with always different strings and thousand rows it does not compress well, quite the opposite, it adds bytes.

As summary, I am super glad you found this module and it helped avoiding crashes in your complex JSON graph but I don't think this module needs any extra reasons that might, or might not, be realistic expectations ... it's all about correctness and if such correctness leads to less worries around complex data, that's a nice extra detail but not the reason people should use this over plain JSON when no recursion or too complex data is used, also because this can't be as fast as native JSON parser/stringifier, due inevitable extra logic involved in the serializer and reviver dance.

I hope this answer makes sense and, once again, thanks for the nice words around this module ❤️
